### ISSUE TITLE
Additional Language File not working

### ISSUE THREAD

**Issue by DependencyHell** [yireo/Yireo_AdditionalLanguageFile#1]
Hello,

I cannot make it works, I'm using Magento CE version 2.1.5
I have a new working theme, but when I add a new file : 
`Company/Themename/Magento_Contact/i18n/en_US_additional.csv`
with :
```
Subject,ABCSubject
Submit,ABCSubmit
```

I cannot see updates

**Comment by jissereitsma** [comment]
Is the content in your post really the contents of your CSV file? Because it does not match the syntax of Magento CSV files.

**Comment by jissereitsma** [comment]
I assume your theme `Company/Themename` is confirmed to be working. Because your naming scheme suggests that you are using the `app/code` folder, while actually `composer` is the recommended way for all packages, let's say that the theme folder is called `$themename`. What you are saying is that a file `$themename/Magento_Contact/i18n/en_US_additional.csv` is not working. It is my understanding that Magento by default does not support `i18n` per module in themes anyway. So, your approach seems to suggest that a simple override like `$themename/Magento_Contact/i18n/en_US.csv` should be working, and this module should allow for the same trick but then with a file called `en_US_additional.csv`. In my environment I can't get `$themename/Magento_Contact/i18n/en_US.csv` to work either. So it seems to me that your problem is not with this module, but the assumption that the core allows `i18n` overrides per module in your theme.

What does work is to have a file `$themename/i18n/en_US.csv` in your theme. And this module allows you to extend from this to have a file `$themename/i18n/en_US_additional.csv`.

**Comment by DependencyHell** [comment]
I used composer to install your module, but I'm building the theme directly into the app/design folder.
My mistake was I didn't understand that Magento does not support `i18n` per module in themes... as you said, so thanks for this part.

Now, I had it working this way : `$themename/i18n/en_US_additional.csv`, with the `en_US` language file.
I'm just having another issue if I use a language that had a previous language pack installed, it is not working due to Magento priorities

**Comment by yireo** [comment]
Thanks for the update!
